<?php

namespace AppBundle\Repository;

/**
 * TablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablesRepository extends \Doctrine\ORM\EntityRepository
{
}
